// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdecidkqlccaeyabdysh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkZWNpZGtxbGNjYWV5YWJkeXNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzI4MDAsImV4cCI6MjA3MDI0ODgwMH0.I4LIBN3IlZhCfNQE_yJp1c9pGl8-3I_Dmw8T6Ac6Za8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});